### ISSUE TITLE
problem with successive scheduled task

### ISSUE THREAD

**Issue by JCVacher** [ExtensiveAutomation/extensiveautomation-server#23]
When I try to use the scheduler to run many times a task, only the 1st execution is done.
I've tried with 'successive' and 'every' (I try with and without a number of runs)

I have client 21.0.0, and server 21.4.0
My task is a TestPlan with 2 TestSuites

some logs: 

2020-10-27 15:42:59,639 - INFO - User Registered: ConnID=2 Addr=('127.0.0.1', 61031) Login=admin
2020-10-27 15:44:39,012 - INFO - Task registered with id 6
2020-10-27 15:44:39,015 - INFO - Starting test 6
2020-10-27 15:45:06,089 - INFO - Task re-scheduled with id 7
2020-10-27 15:45:06,090 - INFO - Starting test 7
2020-10-27 15:45:06,101 - ERROR - Task > prepare: unable to create the main te: startswith first arg must be bytes or a tuple of bytes, not str
2020-10-27 15:45:06,237 - ERROR - Task > run: unable to prepare test
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/serverengine/TaskManager.py", line 1462, in prepare
    var_path=Settings.get('Paths', 'testsresults')
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModel.py", line 104, in createTestExecutable
    var_path)
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModel.py", line 881, in createTestPlan
    parameters=parameters, user=userName)
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModelCommon.py", line 327, in loadDataset
    if pr['value'].startswith('undefined:/'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/serverengine/TaskManager.py", line 2024, in run
    testready = self.prepare(envTmp=False)
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/serverengine/TaskManager.py", line 1467, in prepare
    raise Exception(getBackTrace())
Exception: Traceback (most recent call last):
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/serverengine/TaskManager.py", line 1462, in prepare
    var_path=Settings.get('Paths', 'testsresults')
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModel.py", line 104, in createTestExecutable
    var_path)
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModel.py", line 881, in createTestPlan
    parameters=parameters, user=userName)
  File "/mnt/c/temp/linuxFolder/thingpark-integration-automation/extensiveautomation-server/src/ea/testcreatorlib/TestModelCommon.py", line 327, in loadDataset
    if pr['value'].startswith('undefined:/'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by dmachard** [comment]
- Could you provide the python version in server side ?
- Same behaviour with the v22.1.0 version of the server ?

**Comment by JCVacher** [comment]
Server runs on Python 3.6.9
Sorry, I haven't tested on the last version... (I don't test because in short time I haven't time to update my server, and I see nothing about scheduled task in release notes)

**Comment by JCVacher** [comment]
I've just tested with version 22.1.0: the problem is also present in this version.

**Comment by dmachard** [comment]
Reproduced in my side, just to be sure are you using "dataset" inputs in your test plan ?

**Comment by JCVacher** [comment]
Hello
Yes we use "dataset" input in our tests
